# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083b80fe615bd102f2b7450b964db36c3210a8d6a017891c6df8dc24e6c7bbd8b559550089d3f1cf9d7d3c730ed9d37cbb17590b1da1955e0d0810c2cb21ef6e

test:
  secret_key_base: 9b9243f5a303015026e1099b3c2381c9ae8b9e146205f0fac6211110edd3a314a40ebd053a3bc3f760bfb6500431e7822202d4a0c12f482963429ebd79e940a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
